### ISSUE TITLE
Missing public attribute for copylayer

### ISSUE THREAD

**Issue by pjs-f** [interkosmos/eggx-procall-2003#1]
Hi! In the file procall.f90 is missing the line:

`public :: copylayer`

On the other hand, is there an interface for winname?

Cheers!

**Comment by interkosmos** [comment]
Thank you for reporting. A C binding interface to `eggx_winname()` has been added, just call:

```fortran
use :: eggx
integer :: rc

[...]

rc = eggx_winname(win, 'example title' // c_null_char)
```

The function interface accepts only a single (format) string without any further arguments.
